version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-store-portal-main"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mq3eebwnc4qm"
s3_prefix = "test-store-portal-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
disable_rollback = true

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "test-store-portal-main"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mq3eebwnc4qm"
s3_prefix = "test-store-portal-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
disable_rollback = true

[stage]
[stage.deploy]
[stage.deploy.parameters]
stack_name = "test-store-portal-stage"
s3_bucket = "sam-cli-suntec-s3-samclisourcebucket-g65n9kwrflxz"
s3_prefix = "test-store-portal-stage"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
disable_rollback = true

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "test-store-portal-prod"
s3_bucket = "sam-cli-suntec-s3-samclisourcebucket-g65n9kwrflxz"
s3_prefix = "test-store-portal-prod"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
disable_rollback = true